-- V1__init_schema.sql
-- MySQL 8.0 / InnoDB / utf8mb4

CREATE TABLE IF NOT EXISTS script (
  id varchar(64) NOT NULL,
  name varchar(255) NOT NULL,
  description text,
  status varchar(32) NOT NULL,
  current_version_id varchar(64) DEFAULT NULL,
  created_time datetime NOT NULL,
  updated_time datetime NOT NULL,
  created_by varchar(64) DEFAULT NULL,
  updated_by varchar(64) DEFAULT NULL,
  deleted tinyint NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  KEY idx_script_status (status),
  KEY idx_script_current_version_id (current_version_id),
  KEY idx_script_created_time (created_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS script_version (
  id varchar(64) NOT NULL,
  script_id varchar(64) NOT NULL,
  version_no int NOT NULL,
  version_status varchar(32) NOT NULL,
  description text,
  published_at datetime DEFAULT NULL,
  created_time datetime NOT NULL,
  updated_time datetime NOT NULL,
  created_by varchar(64) DEFAULT NULL,
  updated_by varchar(64) DEFAULT NULL,
  deleted tinyint NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_script_version_no (script_id, version_no),
  KEY idx_script_version_script_id (script_id),
  KEY idx_script_version_status (version_status),
  KEY idx_script_version_published_at (published_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS raw_import_file (
  id varchar(64) NOT NULL,
  import_type varchar(32) NOT NULL,
  original_file_name varchar(255) NOT NULL,
  file_hash varchar(128) DEFAULT NULL,
  file_size bigint DEFAULT NULL,
  charset varchar(32) DEFAULT NULL,
  content longtext NOT NULL,
  status varchar(32) NOT NULL,
  confirmed_script_id varchar(64) DEFAULT NULL,
  confirmed_version_id varchar(64) DEFAULT NULL,
  created_time datetime NOT NULL,
  updated_time datetime NOT NULL,
  created_by varchar(64) DEFAULT NULL,
  updated_by varchar(64) DEFAULT NULL,
  deleted tinyint NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  KEY idx_raw_import_file_type (import_type),
  KEY idx_raw_import_file_hash (file_hash),
  KEY idx_raw_import_file_status (status),
  KEY idx_raw_import_file_version_id (confirmed_version_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS import_log (
  id varchar(64) NOT NULL,
  raw_import_file_id varchar(64) DEFAULT NULL,
  script_id varchar(64) DEFAULT NULL,
  script_version_id varchar(64) DEFAULT NULL,
  import_type varchar(32) NOT NULL,
  stage varchar(32) NOT NULL,
  status varchar(32) NOT NULL,
  message text,
  detail_json longtext,
  warning_json longtext,
  created_time datetime NOT NULL,
  created_by varchar(64) DEFAULT NULL,
  deleted tinyint NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  KEY idx_import_log_file_id (raw_import_file_id),
  KEY idx_import_log_version_id (script_version_id),
  KEY idx_import_log_stage (stage),
  KEY idx_import_log_status (status),
  KEY idx_import_log_created_time (created_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS step_definition (
  id varchar(64) NOT NULL,
  script_id varchar(64) NOT NULL,
  script_version_id varchar(64) NOT NULL,
  parent_step_id varchar(64) DEFAULT NULL,
  step_type varchar(32) NOT NULL,
  name varchar(255) NOT NULL,
  sort_no int NOT NULL,
  request_method varchar(16) DEFAULT NULL,
  request_url text,
  request_config longtext,
  assertion_config longtext,
  extractor_config longtext,
  enabled tinyint NOT NULL DEFAULT 1,
  created_time datetime NOT NULL,
  updated_time datetime NOT NULL,
  created_by varchar(64) DEFAULT NULL,
  updated_by varchar(64) DEFAULT NULL,
  deleted tinyint NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  KEY idx_step_def_script_version_id (script_version_id),
  KEY idx_step_def_script_id (script_id),
  KEY idx_step_def_parent_step_id (parent_step_id),
  KEY idx_step_def_sort_no (sort_no),
  KEY idx_step_def_step_type (step_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS step_request_config (
  id varchar(64) NOT NULL,
  step_id varchar(64) NOT NULL,
  method varchar(16) DEFAULT NULL,
  url_template longtext,
  protocol_type varchar(32) DEFAULT NULL,
  content_type varchar(255) DEFAULT NULL,
  body_format varchar(32) DEFAULT NULL,
  charset varchar(32) DEFAULT NULL,
  timeout_ms int DEFAULT NULL,
  follow_redirect char(1) NOT NULL DEFAULT '1',
  config_json longtext,
  created_time datetime NOT NULL,
  updated_time datetime NOT NULL,
  created_by varchar(64) DEFAULT NULL,
  updated_by varchar(64) DEFAULT NULL,
  deleted tinyint NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_step_request_config_step (step_id),
  KEY idx_step_request_config_method (method),
  KEY idx_step_request_config_protocol (protocol_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS step_payload_content (
  id varchar(64) NOT NULL,
  step_id varchar(64) NOT NULL,
  direction varchar(16) NOT NULL,
  location varchar(32) NOT NULL,
  content_format varchar(32) DEFAULT NULL,
  raw_content longtext,
  parsed_content_json longtext,
  content_hash varchar(128) DEFAULT NULL,
  created_time datetime NOT NULL,
  updated_time datetime NOT NULL,
  created_by varchar(64) DEFAULT NULL,
  updated_by varchar(64) DEFAULT NULL,
  deleted tinyint NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_step_payload_content (step_id, direction, location),
  KEY idx_step_payload_content_step_id (step_id),
  KEY idx_step_payload_content_direction (direction),
  KEY idx_step_payload_content_location (location)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS field_config (
  id varchar(64) NOT NULL,
  script_id varchar(64) NOT NULL,
  script_version_id varchar(64) NOT NULL,
  step_id varchar(64) NOT NULL,
  field_scope varchar(32) NOT NULL,
  field_path varchar(1000) DEFAULT NULL,
  field_key varchar(255) DEFAULT NULL,
  stable_field_key varchar(500) DEFAULT NULL,
  field_name varchar(255) DEFAULT NULL,
  data_type varchar(64) DEFAULT NULL,
  required tinyint NOT NULL DEFAULT 0,
  array_flag tinyint NOT NULL DEFAULT 0,
  `sensitive` tinyint NOT NULL DEFAULT 0,
  description text,
  created_time datetime NOT NULL,
  updated_time datetime NOT NULL,
  created_by varchar(64) DEFAULT NULL,
  updated_by varchar(64) DEFAULT NULL,
  deleted tinyint NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  KEY idx_field_cfg_script_version_id (script_version_id),
  KEY idx_field_cfg_step_id (step_id),
  KEY idx_field_cfg_scope (field_scope),
  KEY idx_field_cfg_stable_key (stable_field_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS script_field_default (
  id varchar(64) NOT NULL,
  script_id varchar(64) NOT NULL,
  script_version_id varchar(64) NOT NULL,
  field_config_id varchar(64) NOT NULL,
  default_value longtext,
  value_source varchar(64) DEFAULT NULL,
  created_time datetime NOT NULL,
  updated_time datetime NOT NULL,
  created_by varchar(64) DEFAULT NULL,
  updated_by varchar(64) DEFAULT NULL,
  deleted tinyint NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_script_field_default (script_version_id, field_config_id),
  KEY idx_script_default_script_id (script_id),
  KEY idx_script_default_field_config_id (field_config_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS tree_cache (
  id varchar(64) NOT NULL,
  owner_type varchar(32) NOT NULL,
  owner_id varchar(64) NOT NULL,
  script_version_id varchar(64) NOT NULL,
  step_id varchar(64) DEFAULT NULL,
  direction varchar(16) DEFAULT NULL,
  location varchar(32) DEFAULT NULL,
  field_config_version int DEFAULT NULL,
  tree_json longtext NOT NULL,
  tree_hash varchar(128) DEFAULT NULL,
  created_time datetime NOT NULL,
  updated_time datetime NOT NULL,
  created_by varchar(64) DEFAULT NULL,
  updated_by varchar(64) DEFAULT NULL,
  deleted tinyint NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  KEY idx_tree_cache_owner (owner_type, owner_id),
  KEY idx_tree_cache_version_id (script_version_id),
  KEY idx_tree_cache_step_id (step_id),
  KEY idx_tree_cache_direction_location (direction, location)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS case_data_set (
  id varchar(64) NOT NULL,
  script_id varchar(64) NOT NULL,
  script_version_id varchar(64) NOT NULL,
  name varchar(255) NOT NULL,
  description text,
  status varchar(32) NOT NULL,
  created_time datetime NOT NULL,
  updated_time datetime NOT NULL,
  created_by varchar(64) DEFAULT NULL,
  updated_by varchar(64) DEFAULT NULL,
  deleted tinyint NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  KEY idx_case_data_set_script_id (script_id),
  KEY idx_case_data_set_script_version_id (script_version_id),
  KEY idx_case_data_set_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS test_case (
  id varchar(64) NOT NULL,
  system_id varchar(64) DEFAULT NULL,
  script_id varchar(64) NOT NULL,
  script_version_id varchar(64) NOT NULL,
  case_code varchar(128) DEFAULT NULL,
  case_name varchar(255) NOT NULL,
  module_id varchar(64) DEFAULT NULL,
  description text,
  status varchar(32) NOT NULL,
  tags longtext,
  owner_id varchar(64) DEFAULT NULL,
  created_time datetime NOT NULL,
  updated_time datetime NOT NULL,
  created_by varchar(64) DEFAULT NULL,
  updated_by varchar(64) DEFAULT NULL,
  deleted tinyint NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_test_case_code (system_id, case_code),
  KEY idx_test_case_script_id (script_id),
  KEY idx_test_case_version_id (script_version_id),
  KEY idx_test_case_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS case_field_value (
  id varchar(64) NOT NULL,
  case_data_set_id varchar(64) NOT NULL,
  case_id varchar(64) DEFAULT NULL,
  script_version_id varchar(64) DEFAULT NULL,
  step_id varchar(64) DEFAULT NULL,
  field_config_id varchar(64) NOT NULL,
  field_id varchar(64) DEFAULT NULL,
  field_code_snapshot varchar(255) DEFAULT NULL,
  field_path_snapshot varchar(1000) DEFAULT NULL,
  raw_input longtext,
  value longtext,
  original_value longtext,
  value_mode varchar(32) DEFAULT NULL,
  value_source varchar(64) DEFAULT NULL,
  is_parameterization char(1) DEFAULT NULL,
  variables_json longtext,
  is_send char(1) DEFAULT NULL,
  version int NOT NULL DEFAULT 0,
  created_time datetime NOT NULL,
  updated_time datetime NOT NULL,
  created_by varchar(64) DEFAULT NULL,
  updated_by varchar(64) DEFAULT NULL,
  deleted tinyint NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_case_field_value (case_data_set_id, field_config_id),
  UNIQUE KEY uk_case_field (case_id, step_id, field_id),
  KEY idx_case_field_value_case_id (case_id),
  KEY idx_case_field_value_version_id (script_version_id),
  KEY idx_case_field_value_step_id (step_id),
  KEY idx_case_field_value_field_config_id (field_config_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS execution_plan (
  id varchar(64) NOT NULL,
  system_id varchar(64) DEFAULT NULL,
  plan_name varchar(255) NOT NULL,
  env_id varchar(64) DEFAULT NULL,
  engine_version varchar(16) DEFAULT NULL,
  run_mode varchar(32) NOT NULL,
  schedule_cron varchar(128) DEFAULT NULL,
  case_run_mode varchar(32) NOT NULL,
  max_concurrency int DEFAULT NULL,
  failure_strategy varchar(32) DEFAULT NULL,
  retry_count int DEFAULT NULL,
  status varchar(32) NOT NULL,
  description text,
  created_time datetime NOT NULL,
  updated_time datetime NOT NULL,
  created_by varchar(64) DEFAULT NULL,
  updated_by varchar(64) DEFAULT NULL,
  deleted tinyint NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  KEY idx_execution_plan_system_id (system_id),
  KEY idx_execution_plan_env_id (env_id),
  KEY idx_execution_plan_status (status),
  KEY idx_execution_plan_created_time (created_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS execution_plan_case (
  id varchar(64) NOT NULL,
  plan_id varchar(64) NOT NULL,
  case_id varchar(64) NOT NULL,
  script_id varchar(64) NOT NULL,
  script_version_id varchar(64) NOT NULL,
  env_id varchar(64) DEFAULT NULL,
  order_no int NOT NULL,
  enabled char(1) NOT NULL DEFAULT '1',
  config_json longtext,
  created_time datetime NOT NULL,
  updated_time datetime NOT NULL,
  created_by varchar(64) DEFAULT NULL,
  updated_by varchar(64) DEFAULT NULL,
  deleted tinyint NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_execution_plan_case (plan_id, case_id),
  KEY idx_execution_plan_case_plan_id (plan_id),
  KEY idx_execution_plan_case_case_id (case_id),
  KEY idx_execution_plan_case_version_id (script_version_id),
  KEY idx_execution_plan_case_order_no (order_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS execution_plan_instance (
  id varchar(64) NOT NULL,
  plan_id varchar(64) NOT NULL,
  trigger_type varchar(32) NOT NULL,
  trigger_time datetime NOT NULL,
  triggered_by varchar(64) DEFAULT NULL,
  env_id varchar(64) DEFAULT NULL,
  status varchar(32) NOT NULL,
  total_count int NOT NULL DEFAULT 0,
  success_count int NOT NULL DEFAULT 0,
  failed_count int NOT NULL DEFAULT 0,
  skipped_count int NOT NULL DEFAULT 0,
  duration_ms bigint DEFAULT NULL,
  start_time datetime DEFAULT NULL,
  end_time datetime DEFAULT NULL,
  summary_json longtext,
  error_message longtext,
  created_time datetime NOT NULL,
  updated_time datetime NOT NULL,
  created_by varchar(64) DEFAULT NULL,
  updated_by varchar(64) DEFAULT NULL,
  deleted tinyint NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  KEY idx_plan_instance_plan_id (plan_id),
  KEY idx_plan_instance_status (status),
  KEY idx_plan_instance_trigger_time (trigger_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS execution_task (
  id varchar(64) NOT NULL,
  plan_instance_id varchar(64) DEFAULT NULL,
  plan_id varchar(64) DEFAULT NULL,
  case_id varchar(64) DEFAULT NULL,
  script_id varchar(64) NOT NULL,
  script_version_id varchar(64) NOT NULL,
  env_id varchar(64) DEFAULT NULL,
  engine_version varchar(16) DEFAULT NULL,
  execution_id varchar(64) DEFAULT NULL,
  status varchar(32) NOT NULL,
  order_no int DEFAULT NULL,
  retry_count int NOT NULL DEFAULT 0,
  max_retry_count int NOT NULL DEFAULT 0,
  executor_node_id varchar(64) DEFAULT NULL,
  dispatch_time datetime DEFAULT NULL,
  start_time datetime DEFAULT NULL,
  end_time datetime DEFAULT NULL,
  duration_ms bigint DEFAULT NULL,
  error_message longtext,
  created_time datetime NOT NULL,
  updated_time datetime NOT NULL,
  created_by varchar(64) DEFAULT NULL,
  updated_by varchar(64) DEFAULT NULL,
  deleted tinyint NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  KEY idx_execution_task_instance_id (plan_instance_id),
  KEY idx_execution_task_plan_id (plan_id),
  KEY idx_execution_task_case_id (case_id),
  KEY idx_execution_task_script_version_id (script_version_id),
  KEY idx_execution_task_execution_id (execution_id),
  KEY idx_execution_task_status (status),
  KEY idx_execution_task_start_time (start_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS flow_execution_record (
  id varchar(64) NOT NULL,
  task_id varchar(64) DEFAULT NULL,
  plan_id varchar(64) DEFAULT NULL,
  plan_instance_id varchar(64) DEFAULT NULL,
  case_id varchar(64) DEFAULT NULL,
  script_id varchar(64) NOT NULL,
  script_version_id varchar(64) NOT NULL,
  env_id varchar(64) DEFAULT NULL,
  execution_type varchar(32) NOT NULL,
  status varchar(32) NOT NULL,
  trace_id varchar(128) DEFAULT NULL,
  duration_ms bigint DEFAULT NULL,
  env_snapshot_json longtext,
  variable_snapshot_json longtext,
  final_variable_snapshot_json longtext,
  result_summary_json longtext,
  error_code varchar(64) DEFAULT NULL,
  error_message longtext,
  triggered_by varchar(64) DEFAULT NULL,
  start_time datetime DEFAULT NULL,
  end_time datetime DEFAULT NULL,
  created_time datetime NOT NULL,
  updated_time datetime NOT NULL,
  created_by varchar(64) DEFAULT NULL,
  updated_by varchar(64) DEFAULT NULL,
  deleted tinyint NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  KEY idx_flow_record_task_id (task_id),
  KEY idx_flow_record_plan_instance_id (plan_instance_id),
  KEY idx_flow_record_case_id (case_id),
  KEY idx_flow_record_script_version_id (script_version_id),
  KEY idx_flow_record_execution_type (execution_type),
  KEY idx_flow_record_status (status),
  KEY idx_flow_record_start_time (start_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS step_execution_snapshot (
  id varchar(64) NOT NULL,
  execution_id varchar(64) NOT NULL,
  step_id varchar(64) NOT NULL,
  step_order_no int DEFAULT NULL,
  step_name varchar(255) DEFAULT NULL,
  step_type varchar(32) DEFAULT NULL,
  status varchar(32) NOT NULL,
  resolved_method varchar(16) DEFAULT NULL,
  resolved_url longtext,
  resolved_query_json longtext,
  resolved_request_headers_json longtext,
  resolved_request_cookies_json longtext,
  resolved_request_body longtext,
  response_status_code int DEFAULT NULL,
  response_headers_json longtext,
  response_cookies_json longtext,
  response_body longtext,
  response_content_type varchar(255) DEFAULT NULL,
  response_time_ms bigint DEFAULT NULL,
  raw_input_snapshot_json longtext,
  resolved_field_value_json longtext,
  extracted_variables_json longtext,
  assert_result_json longtext,
  execution_log longtext,
  error_code varchar(64) DEFAULT NULL,
  error_message longtext,
  start_time datetime DEFAULT NULL,
  end_time datetime DEFAULT NULL,
  created_time datetime NOT NULL,
  updated_time datetime NOT NULL,
  created_by varchar(64) DEFAULT NULL,
  updated_by varchar(64) DEFAULT NULL,
  deleted tinyint NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  KEY idx_step_snapshot_execution_id (execution_id),
  KEY idx_step_snapshot_step_id (step_id),
  KEY idx_step_snapshot_status (status),
  KEY idx_step_snapshot_start_time (start_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
